In [2]:
import torch
import torch.nn as nn
import numpy as np


# Define your deep learning model
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc1 = nn.Linear(64, 128)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(128, 64)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(64, 10)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        return x

def init_weights():
    # Set a random seed for reproducibility
    seed = 42
    torch.manual_seed(seed)
    np.random.seed(seed)

    # Create an instance of your model
    model = MyModel()
    
    # Apply Xavier Normal Initialization to the model's weights
    def xavier_init(m):
        if isinstance(m, nn.Linear):
            nn.init.xavier_normal_(m.weight)
    
    model.apply(xavier_init)
    
    # The model's weights are now initialized with Xavier initialization and the specified seed
    # Print the weights of the model
    for name, param in model.named_parameters():
        if param.requires_grad:
            print(f"Layer: {name}, Size: {param.size()}, Values: \n{param.data}")

In [19]:
init_weights()

Layer: fc1.weight, Size: torch.Size([128, 64]), Values: 
tensor([[-4.2759e-02, -2.8724e-02,  3.6905e-02,  ..., -3.8945e-02,
          2.8025e-02,  1.4302e-02],
        [ 8.9404e-02, -5.6625e-02,  3.2686e-02,  ..., -1.1268e-01,
         -4.8466e-02, -8.7921e-02],
        [ 4.8338e-04, -9.5224e-02,  1.0762e-01,  ...,  1.2467e-04,
         -6.3149e-02,  8.2928e-02],
        ...,
        [-1.4036e-01,  1.0117e-01, -5.0051e-02,  ...,  1.3005e-01,
         -5.0149e-02, -1.2380e-01],
        [ 1.3158e-02, -1.5636e-01, -7.3109e-02,  ...,  1.2204e-01,
         -1.0308e-01, -3.3708e-02],
        [ 4.8054e-02, -1.7660e-01, -3.2060e-02,  ...,  5.6618e-03,
          1.3645e-02,  4.0833e-02]])
Layer: fc1.bias, Size: torch.Size([128]), Values: 
tensor([ 0.0628, -0.0145, -0.0114,  0.1147,  0.0276,  0.0002, -0.1114,  0.0087,
        -0.1064, -0.0297,  0.0745, -0.0642, -0.0079, -0.0304, -0.0322,  0.0884,
        -0.0129, -0.0373, -0.1210, -0.0102, -0.1105, -0.0516, -0.0881,  0.0343,
        -0.0832,  0.

# Init BatchNorm2d layer

In [20]:
import torch
import torch.nn as nn

# Create a BatchNorm2d layer
batch_norm = nn.BatchNorm2d(64)

# Initialize your model and add the BatchNorm2d layer
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, padding=1)
        self.batch_norm = nn.BatchNorm2d(64)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.conv1(x)
        x = self.batch_norm(x)
        x = self.relu(x)
        return x

def init_BatchNorm2d():
    # Initialize and use the model
    model = MyModel()
    input_tensor = torch.randn(16, 3, 32, 32)  # Example input data
    output = model(input_tensor)

     # Print the weights of the model
    for name, param in model.named_parameters():
        if param.requires_grad:
            print(f"Layer: {name}, Size: {param.size()}, Values: \n{param.data}")


In [21]:
init_BatchNorm2d()

Layer: conv1.weight, Size: torch.Size([64, 3, 3, 3]), Values: 
tensor([[[[-1.5146e-01, -2.0709e-02,  1.8214e-01],
          [-7.3134e-02, -1.7141e-01,  2.3499e-02],
          [ 7.5109e-02, -1.2889e-01, -8.3142e-02]],

         [[ 1.5475e-01, -4.0861e-02,  1.9535e-03],
          [-1.0660e-01,  8.6399e-02, -9.9515e-02],
          [ 1.6471e-01,  6.6744e-02,  1.2981e-01]],

         [[-9.1079e-02,  9.9150e-02,  1.7846e-01],
          [-1.0063e-02, -1.4139e-01,  1.6156e-01],
          [-1.9650e-02, -1.4676e-01,  9.8987e-02]]],


        [[[-1.6534e-01, -7.0416e-02,  1.0174e-01],
          [ 4.2945e-02,  7.6808e-02,  1.6228e-01],
          [ 4.4834e-02,  5.8366e-02,  5.2431e-02]],

         [[-7.7098e-02, -7.3470e-02, -7.6232e-02],
          [-1.0049e-01,  8.1928e-02,  1.6835e-01],
          [ 1.5860e-01,  9.0366e-03,  1.6863e-01]],

         [[-1.1810e-01, -8.2787e-02,  8.4865e-02],
          [ 1.7382e-01, -7.2161e-02, -2.7380e-02],
          [-1.2932e-01,  4.9316e-02,  6.5063e-02]]],


   